spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: service-01
          uri: http://localhost:8081/api
          predicates:
            - Path=/first/**
        - id: service-02
          uri: http://localhost:8082/api
          predicates:
            - Path=/second/**